language: r
os: linux
dist: xenial
r:
  - oldrel
  - release
  - devel
  - bioc-devel

sudo: required

before_install:
  - sudo apt-get update -y
  - sudo apt-get install -y libudunits2-dev
  - sudo apt-get install -y libgdal-dev libproj-dev
  - sudo apt-get install -y libgeos-dev libfontconfig1-dev

r_packages:
  - sp
  - rgdal
  - rgeos
  - sf

script:
  - R -e "source('tests/testthat.R')"

