language: r
os: linux
dist: xenial
r:
  - oldrel
  - release
  - devel
  - bioc-devel
r_packages:
  - sp
  - rgdal
  - rgeos
apt_packages:
  - libxml2-dev
install: skip
script:
  - R -e "source('tests/testthat.R')"
